versioning

diff --git a/.github/workflows/version-bumper.yml b/.github/workflows/version-bumper.yml
--- a/.github/workflows/version-bumper.yml
+++ b/.github/workflows/version-bumper.yml
@@ -74,6 +74,13 @@ jobs:
             echo "Failed to copy pyproject.toml"
             exit 1
           fi
+      - name: Update Helm Publisher workflow with version branches
+        run: |
+          # adding the version branches to options in the helm-publisher.yml file
+          if ! uv run python .github/scripts/update_helm_publisher.py; then
+            echo "Failed to update helm bumper workflow"
+            exit 1
+          fi
       - name: Commit version changes
         run: |
           # Add all the version-updated files
@@ -85,13 +92,6 @@ jobs:
           # Push to version branch
           git push -f origin ${{ steps.create-branch.outputs.branch_name }}
           echo "✅ Version changes committed to version branch"
-      - name: Update Helm Publisher workflow with version branches
-        run: |
-          # adding the version branches to options in the helm-publisher.yml file
-          if ! uv run python .github/scripts/update_helm_publisher.py; then
-            echo "Failed to update helm bumper workflow"
-            exit 1
-          fi
       - name: Create Pull Request
         uses: peter-evans/create-pull-request@v5
         with:
